# Generated by Django 5.2.8 on 2025-11-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_texte',
            new_name='message_text',
        ),
    ]
